{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"node\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSD",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * node_filesystem_avail_bytes{instance=~\"$instance\", fstype!~\"tmpfs|overlay\"} / node_filesystem_size_bytes{instance=~\"$instance\", fstype!~\"tmpfs|overlay\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сеть",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\", device!~\"lo\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance\", device!~\"lo\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}